# pg_hba.conf

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Aceptar conexiones TCP/IP desde CUALQUIER dirección (incluyendo la red de Docker y localhost)
# si se proporciona una contraseña válida con el método de autenticación moderno.
# Esta debe ser la PRIMERA regla "host".
host    all             all             0.0.0.0/0               scram-sha-256
host    all             all             ::/0                    scram-sha-256

# Mantener estas reglas para conexiones internas es una buena práctica.
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust