# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Permite cualquier conexión local (dentro del contenedor) sin contraseña.
local   all             all                                     trust

# Permite que cualquier usuario se conecte desde dentro del contenedor vía TCP/IP.
host    all             all             127.0.0.1/32            trust

# Permite conexiones desde la red de Docker (para conexiones desde el host)
host    all             all             172.16.0.0/12           scram-sha-256

# Permite al usuario de la aplicación conectarse desde cualquier IP.
host    all             reservas_user   0.0.0.0/0               scram-sha-256
host    all             reservas_user   ::/0                    scram-sha-256