version: '3.8'

services:
  # Servicio de la Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: reservas_user
      POSTGRES_PASSWORD: p4ssw0rd_s3gUr4_2025!
      POSTGRES_DB: reservas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servicio del Backend (Nuestra API Node.js)
  backend:
    container_name: backend_api
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # Servicio del Frontend (Nuestra App React)
  frontend:
    container_name: frontend_client
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
    name: sistema-reservas-pgdata